#!/usr/bin/env python3
"""Fix all 157 remaining wrong-meaning words"""
import re, json

with open("c:/Users/admin/Desktop/vocab-app/words.js", "r", encoding="utf-8") as f:
    text = f.read()

m = re.search(r'const wordDatabase = (.+);', text, re.DOTALL)
data = json.loads(m.group(1))

FIXES = {
    # tud- words (knows; can -> correct forms)
    "tudod": "you know (it)",
    "tudok": "I know; I can",
    "tudsz": "you know; you can",
    "tudjuk": "we know (it)",
    "tudni": "to know",
    "tudta": "he/she knew (it)",
    "tudunk": "we know; we can",
    "tudott": "he/she knew; could",
    "tudn\u00e1": "he/she would know; could",
    "tudnom": "I must know",
    "tudna": "he/she would know; could",
    "tudn\u00e9k": "I would know; I could",
    "tudd": "know! (imperative)",
    "tudtok": "you (plural) know; can",
    "tudhatod": "you can know; you might know",
    "tudlak": "I know you",
    "tud\u00f3s": "scientist; scholar",
    "tudnunk": "we must know",
    "tudtunk": "we knew; we could",

    # meg- words (still; yet -> correct meanings)
    "megy": "to go",
    "megvan": "it is done; it is available",
    "megint": "again",
    "meg\u00e9rtem": "I understood",
    "megmondtam": "I told (you)",
    "meghal": "to die",
    "megmondom": "I will tell (you)",
    "megtal\u00e1lni": "to find",
    "megn\u00e9zem": "I will look at (it)",
    "meglepet\u00e9s": "surprise",
    "megl\u00e1tjuk": "we will see",
    "megmutatom": "I will show (it)",
    "meg\u00edgérem": "I promise",
    "megtenni": "to do; to take action",
    "meglesz": "will be; will have",
    "megt\u00f6rt\u00e9nt": "happened; took place",
    "megteszem": "I will do (it)",
    "megtal\u00e1ljuk": "we will find (it)",
    "megmenteni": "to save; to rescue",
    "megv\u00e1ltozott": "changed",
    "megn\u00e9zni": "to look at; to check",
    "megtal\u00e1ltuk": "we found (it)",
    "megvolt": "it was done; it happened",
    "megs\u00e9r\u00fclt": "was injured; got hurt",
    "megmondani": "to tell; to say",
    "megl\u00e1tod": "you will see (it)",
    "meg\u00e9rteni": "to understand",
    "megegyezt\u00fcnk": "we agreed",
    "megtal\u00e1lta": "he/she found (it)",
    "meg\u00e1ll\u00edtani": "to stop (something)",
    "megtiszteltet\u00e9s": "honor; privilege",
    "megteszi": "he/she does (it)",
    "megvagy": "you're fine; how are you",
    "megkapja": "he/she receives (it)",
    "meg\u00e9rkezett": "he/she arrived",
    "megfelel": "to correspond; to meet (requirements)",
    "megcsin\u00e1lni": "to make; to do; to fix",
    "megtal\u00e1lt\u00e1k": "they found (it)",
    "megj\u00f6tt": "he/she arrived; it came",
    "meg\u00edg\u00e9rtem": "I promised",
    "megteszek": "I will do",
    "megv\u00e9deni": "to defend; to protect",
    "megkapod": "you will receive (it)",
    "megcsin\u00e1lom": "I will make/do (it)",
    "meg\u00f6l": "to kill",
    "megtudja": "he/she finds out; can know",
    "meg\u0151r\u00fclt": "went crazy; insane",
    "megmentette": "he/she saved (him/her)",
    "meg\u00e9rtette": "he/she understood (it)",
    "meg\u00e1llni": "to stop",
    "megk\u00e9rt": "he/she asked",
    "megbesz\u00e9lt\u00fck": "we discussed; we agreed on",
    "megtal\u00e1lja": "he/she will find (it)",
    "megtudni": "to find out",
    "megkapta": "he/she received (it)",
    "megtal\u00e1lom": "I will find (it)",
    "megbesz\u00e9lj\u00fck": "let's discuss; we will discuss",
    "megn\u00e9zz\u00fck": "let's look at (it)",
    "megl\u00e1ttam": "I saw (it)",
    "megpr\u00f3b\u00e1l": "to try; to attempt",
    "megsz\u00f6k\u00f6tt": "escaped; ran away",
    "megt\u00f6rt\u00e9nik": "happens; takes place",
    "megkeresem": "I will look for (it); I will find (it)",
    "megtette": "he/she did (it)",
    "meglep\u0151": "surprising",
    "meg\u00e9ri": "it's worth it; it pays off",
    "megn\u00e9ztem": "I looked at (it)",
    "megadom": "I give (it)",
    "megb\u00edzhat\u00f3": "reliable; trustworthy",
    "megt\u00f6rt\u00e9nni": "to happen",
    "megl\u00e1tja": "he/she will see (it)",
    "megcsin\u00e1ltuk": "we made/did (it)",
    "megtal\u00e1lj\u00e1k": "they will find (it)",
    "megteszed": "you will do (it)",
    "megengedi": "he/she allows (it)",
    "meg\u00e9rted": "you understood (it)",
    "megk\u00e9rdeztem": "I asked",
    "megtenn\u00e9d": "would you do (it)",
    "megjelent": "appeared; was published",
    "meg\u00e9rti": "he/she understands (it)",
    "megl\u00e1tom": "I will see (it)",
    "megtanultam": "I learned",
    "megcsin\u00e1ltad": "you made/did (it)",
    "megk\u00e9rdezem": "I will ask",
    "megk\u00f6sz\u00f6nni": "to thank",
    "megcsin\u00e1ltam": "I made/did (it)",
    "meglehet": "may be; is possible",

    # ki- words (who; out -> correct)
    "kir\u00e1ly": "king",
    "kibaszott": "fucking (intensifier)",
    "kit": "whom (accusative)",
    "kint": "outside; outdoors",
    "kinek": "to whom",
    "kifel\u00e9": "outward; towards outside",
    "kik": "who (plural)",
    "kiv\u00e9ve": "except; excluding",
    "kicsoda": "who (emphatic)",
    "kivel": "with whom",
    "kilenc": "nine",
    "kiv\u00e1l\u00f3": "excellent; outstanding",
    "kiz\u00e1rt": "excluded; ruled out",
    "kider\u00fcl": "it turns out; becomes clear",
    "kinyitni": "to open",
    "kim": "Kim (name)",
    "ki\u00e9": "whose",
    "kinn": "outside; outdoors",
    "kil\u00f3": "kilo; kilogram",
    "kifejez\u00e9s": "expression",

    # kő (stone) words
    "komoly": "serious",
    "kor": "age; time; era",
    "kocsi": "car; carriage",
    "konyh\u00e1ban": "in the kitchen",
    "koncentr\u00e1lj": "concentrate (imperative)",
    "kock\u00e1zatot": "risk (accusative)",

    # neve (don't) words
    "neh\u00e9z": "difficult; hard",
    "nev\u0171": "named; called (adjective)",
    "nehogy": "lest; so that not",
    "nesze": "here you go; take this",
    "negat\u00edv": "negative",
    "negyed": "quarter; fourth",

    # Other wrong words
    "francba": "damn it; to hell with it",
    "es": "and (variant form)",
    "and": "and (English loanword)",
    "k\u00fcl\u00f6nleges": "special; particular",
    "any\u00e1d": "your mother (informal)",
    "r\u00e9g\u00f3ta": "for a long time",
    "j\u00f6ttek": "they came",
    "tal\u00e1l": "to find",
    "gyermek": "child (formal)",
    "ifj\u00fa": "young (formal/literary)",
    "h\u00edvta": "he/she called (him/her)",
    "k\u00f6vetett": "he/she followed",
    "szel": "slice; cut (imperative)",
    "agy": "brain",
    "szerezte": "he/she obtained (it)",
    "oldalt": "to the side; sideways",
    "h\u00edvsz": "you call",
    "leszarom": "I don't give a damn (vulgar)",
    "tea": "tea",
    "teremben": "in the room/hall",
    "tetej\u00e9n": "on top of",
    "lenn": "down; below",
    "lelki": "spiritual; soul (adjective)",
    "lel\u0151tt\u00e9k": "they shot (him/her)",
    "lel\u0151tte": "he/she shot (him/her)",
    "lelke": "his/her soul",
    "lejjebb": "lower; further down",
    "leesett": "fell down",
    "lefek\u00fcdni": "to lie down; to go to bed",
    "legenda": "legend",
    "leg\u00fajabb": "newest; latest",
    "fels\u0151": "upper; top",
    "felk\u00e9sz\u00fclni": "to prepare",
    "felh\u00edvott": "called (by phone); he/she called",
    "felh\u00edvtam": "I called (by phone)",
    "felvenni": "to put on; to record; to hire",
    "sof\u0151r": "driver",
    "tenn\u00e9": "he/she would do/put",
    "templom": "church; temple",
    "tetszene": "would please; would be pleasing",
    "egyb\u0151l": "at once; right away",
    "egyfolyt\u00e1ban": "continuously; non-stop",
    "egyes": "single; one each",
    "egyenese": "straight (adjective)",
    "toj\u00e1s": "egg",
    "meglehet\u0151sen": "considerably; fairly",
    "megold\u00e1s": "solution",
    "megoldani": "to solve",
    "megoldom": "I solve (it)",
    "megoldjuk": "we solve (it)",
    "megpr\u00f3b\u00e1lta": "he/she tried (it)",
    "megpr\u00f3b\u00e1lom": "I try (it)",
    "megpr\u00f3b\u00e1lja": "he/she tries (it)",
    "megpr\u00f3b\u00e1lok": "I try",
    "megpr\u00f3b\u00e1lt": "tried",
    "megpr\u00f3b\u00e1ltam": "I tried",
    "megtal\u00e1ltad": "you found (it)",
    "megtal\u00e1ltam": "I found (it)",
    "megtettem": "I did (it)",
    "megvagyok": "I'm fine",
    "megvannak": "they are done/available",
    "meg\u0151r\u00fclt\u00e9l": "you went crazy",
    "meg\u00e9rtetted": "you understood",
    "meg\u00e9rtettem": "I understood",
    "meg\u00f6l\u00f6m": "I kill",
    "meg\u00f6li": "he/she kills (him/her)",
    "meg\u00f6lik": "they kill him/her",
    "meg\u00f6llek": "I'll kill you",
    "meg\u00f6lnek": "they kill",
    "meg\u00f6lni": "to kill",
    "meg\u00f6lt": "killed",
    "meg\u00f6lt\u00e9k": "they killed",
    "meg\u00f6lte": "he/she killed",
    "meg\u00f6lted": "you killed",
    "meg\u00f6ltem": "I killed",
    "megfelel\u0151": "appropriate; suitable",
    "meghalnak": "they die",
    "meghalni": "to die",
    "meghalok": "I die",
    "meghalsz": "you die",
    "meghalt": "died",
    "meghalt\u00e1l": "you died (informal)",
    "meghaltak": "died (plural)",
    "meghaltam": "I died",
    "meghalunk": "we die",
    "megkaptad": "you received (it)",
    "megkaptam": "I received (it)",
    "megtal\u00e1lj\u00e1k": "they will find (it)",
    "megtal\u00e1lja": "he/she finds (it)",
    "megtal\u00e1lj\u00e1k": "they find (it)",
    "megtal\u00e1lhat\u00f3": "can be found",
    "megtal\u00e1lod": "you find (it)",
    "megtal\u00e1lok": "I find",
    "megtal\u00e1lom": "I find (it)",
    "megtal\u00e1lsz": "you find",
    "megtal\u00e1lt": "found",
    "megtal\u00e1lta": "he/she found (it)",
    "megtal\u00e1lt\u00e1k": "they found (it)",
    "megtal\u00e1lt\u00e1l": "did you find (informal)",
    "megtal\u00e1ltad": "you found (it)",
    "megtal\u00e1ltak": "they found",
    "megtal\u00e1ltam": "I found",
    "megtal\u00e1ltuk": "we found (it)",
    "megtal\u00e1ltunk": "we found",
    "megtal\u00e1lunk": "we find",
    "megtanultam": "I learned",
    "megtudni": "to find out",
    "meg\u00e9ri": "it's worth it",
    "meg\u00e9rteni": "to understand",
    "meg\u00e9rti": "he/she understands",
    "meg\u00e9rtette": "he/she understood",
    "meg\u00e9rtettem": "I understood",
    "meg\u00e9rtetted": "you understood",
    "meg\u00e9rtem": "I understand",
    "meg\u00e9rkezett": "he/she arrived",
    "meg\u00e9rkez\u00e9s": "arrival",
    "megengedi": "he/she allows",
    "megengedni": "to allow",
    "megengedem": "I allow",
    "megengedte": "he/she allowed",
    "megengedtem": "I allowed",
    "megengedn\u00e9m": "I would allow",
    "megengeded": "you allow",
    "megengedj\u00fck": "we allow",
    "megengednek": "they allow",
    "megengedsz": "you allow",
    "megenged": "to allow",
    "megengedj": "allow (imperative)",
    "megengedje": "let him/her allow",
    "megengedj\u00e9k": "let them allow",
    "megengedj\u00e9tek": "you (plural) allow",
    "megengedjetek": "you (plural) allow",
    "megengedj\u00fck": "we allow",
    "megengedj\u00fck": "we allow",
}

fixed = 0
for w in data:
    if w["h"] in FIXES:
        old = w["e"]
        w["e"] = FIXES[w["h"]]
        fixed += 1

print(f"Fixed {fixed} words")

with open("c:/Users/admin/Desktop/vocab-app/words.js", "w", encoding="utf-8") as f:
    f.write("// Hungarian-English vocabulary database\n")
    f.write(f"// {len(data)} words from 5K.csv\n")
    f.write("const wordDatabase = ")
    f.write(json.dumps(data, ensure_ascii=False, indent=2))
    f.write(";\n")
